apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: poc3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: poc3
    spec:
      containers:
      - name: poc3
        image: poc2:latest
        ports:
        - containerPort: 80
