apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: poc5
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: poc5
    spec:
      containers:
      - name: poc5
        image: poc5:latest
        ports:
        - containerPort: 80
