apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc3latest-Deployment
  labels:
    app: poc3latest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poc3latest
  template:
    metadata:
      labels:
        app: poc3latest
    spec:
      containers:
      - name: poc
        image: poc2:latest
        ports:
        - containerPort: 80
