apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: poc4
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: poc4
    spec:
      containers:
      - name: poc4
        image: poc4:latest
        ports:
        - containerPort: 80
