apiVersion: v1
kind: Service
metadata:
  name: poc5
  labels:
    app: poc5
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: poc5
